# Phase 1: Data Understanding & Profiling
## E-Commerce Sales & Customer Analytics Dashboard

This notebook performs detailed profiling on the raw Olist Brazilian E-Commerce dataset. We will load all 9 operational tables and extract:
- Number of rows and columns
- Missing value counts
- Duplicate records count
- Core data types
- Complete Data Dictionary with business definitions

---

In [1]:
import pandas as pd
import numpy as np
import os

# Set dataset folder path
RAW_DATA_DIR = '../data/raw/'
print(f'Raw dataset directory: {RAW_DATA_DIR}')
print(os.listdir(RAW_DATA_DIR))

Raw dataset directory: ../data/raw/
['olist_customers_dataset.csv', 'olist_geolocation_dataset.csv', 'olist_orders_dataset.csv', 'olist_order_items_dataset.csv', 'olist_order_payments_dataset.csv', 'olist_order_reviews_dataset.csv', 'olist_products_dataset.csv', 'olist_sellers_dataset.csv', 'product_category_name_translation.csv']

### Loading the Tables
We will load all the CSV files into pandas dataframes to check their schema.

In [2]:
datasets = {
    'customers': 'olist_customers_dataset.csv',
    'geolocation': 'olist_geolocation_dataset.csv',
    'order_items': 'olist_order_items_dataset.csv',
    'order_payments': 'olist_order_payments_dataset.csv',
    'order_reviews': 'olist_order_reviews_dataset.csv',
    'orders': 'olist_orders_dataset.csv',
    'products': 'olist_products_dataset.csv',
    'sellers': 'olist_sellers_dataset.csv',
    'category_translation': 'product_category_name_translation.csv'
}

dfs = {}
for name, filename in datasets.items():
    filepath = os.path.join(RAW_DATA_DIR, filename)
    dfs[name] = pd.read_csv(filepath)
    print(f'Loaded {name}: {dfs[name].shape[0]} rows, {dfs[name].shape[1]} columns')

Loaded customers: 99441 rows, 5 columns
Loaded geolocation: 1000163 rows, 5 columns
Loaded order_items: 112650 rows, 7 columns
Loaded order_payments: 103886 rows, 5 columns
Loaded order_reviews: 99224 rows, 7 columns
Loaded orders: 99441 rows, 8 columns
Loaded products: 32951 rows, 9 columns
Loaded sellers: 3095 rows, 4 columns
Loaded category_translation: 71 rows, 2 columns

### Detailed Profiling for Every Table
Let's write a function to summarize metadata: dimensions, null counts, duplicate records, and data types.

In [3]:
def profile_table(name, df):
    print('='*50)
    print(f'PROFILE FOR TABLE: {name.upper()}')
    print('='*50)
    print(f'Dimensions: {df.shape[0]} rows, {df.shape[1]} columns\n')
    
    print('--- Data Types and Missing Values ---')
    missing = df.isnull().sum()
    missing_pct = (missing / len(df)) * 100
    types = df.dtypes
    
    profile_df = pd.DataFrame({
        'Data Type': types,
        'Missing Values': missing,
        'Missing %': missing_pct.round(2)
    })
    print(profile_df)
    
    duplicates = df.duplicated().sum()
    print(f'\nDuplicate Records: {duplicates} ({duplicates/len(df)*100:.2f}%)\n')
    
    print('--- Sample Rows ---')
    display(df.head(2))
    print('\n')

for name, df in dfs.items():
    profile_table(name, df)

==================================================
PROFILE FOR TABLE: CUSTOMERS
==================================================
Dimensions: 99441 rows, 5 columns

--- Data Types and Missing Values ---
                         Data Type  Missing Values  Missing %
customer_id                 object               0        0.0
customer_unique_id          object               0        0.0
customer_zip_code_prefix     int64               0        0.0
customer_city               object               0        0.0
customer_state              object               0        0.0

Duplicate Records: 0 (0.00%)

--- Sample Rows ---

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP

==================================================
PROFILE FOR TABLE: GEOLOCATION
==================================================
Dimensions: 1000163 rows, 5 columns

--- Data Types and Missing Values ---
                            Data Type  Missing Values  Missing %
geolocation_zip_code_prefix     int64               0        0.0
geolocation_lat               float64               0        0.0
geolocation_lng               float64               0        0.0
geolocation_city               object               0        0.0
geolocation_state              object               0        0.0

Duplicate Records: 261831 (26.18%)

--- Sample Rows ---

,geolocation_zip_code_prefix,geolocation_lat,geolocation_lng,geolocation_city,geolocation_state
0,1037,-23.545621,-46.639292,sao paulo,SP
1,1046,-23.546081,-46.644820,sao paulo,SP

==================================================
PROFILE FOR TABLE: ORDER_ITEMS
==================================================
Dimensions: 112650 rows, 7 columns

--- Data Types and Missing Values ---
                    Data Type  Missing Values  Missing %
order_id               object               0        0.0
order_item_id           int64               0        0.0
product_id             object               0        0.0
seller_id              object               0        0.0
shipping_limit_date    object               0        0.0
price                 float64               0        0.0
freight_value         float64               0        0.0

Duplicate Records: 0 (0.00%)

--- Sample Rows ---

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.9,13.29
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.9,19.93

==================================================
PROFILE FOR TABLE: ORDER_PAYMENTS
==================================================
Dimensions: 103886 rows, 5 columns

--- Data Types and Missing Values ---
                     Data Type  Missing Values  Missing %
order_id                object               0        0.0
payment_sequential       int64               0        0.0
payment_type            object               0        0.0
payment_installments     int64               0        0.0
payment_value          float64               0        0.0

Duplicate Records: 0 (0.00%)

--- Sample Rows ---

,order_id,payment_sequential,payment_type,payment_installments,payment_value
0,b81ef226f3fe1789b1e8b2acac839d17,1,credit_card,8,99.33
1,a9810da82917af2d9aefd1278f1dcfa0,1,credit_card,1,24.39

==================================================
PROFILE FOR TABLE: ORDER_REVIEWS
==================================================
Dimensions: 99224 rows, 7 columns

--- Data Types and Missing Values ---
                        Data Type  Missing Values  Missing %
review_id                  object               0       0.00
order_id                   object               0       0.00
review_score                int64               0       0.00
review_comment_title       object           87656      88.34
review_comment_message     object           58247      58.70
review_creation_date       object               0       0.00
review_answer_timestamp    object               0       0.00

Duplicate Records: 0 (0.00%)

--- Sample Rows ---

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
0,7bc2406110b926393aa56f80a40eba40,73fc7af87114b39712e6da79b0a377eb,4,NaN,NaN,2018-01-18 00:00:00,2018-01-18 21:46:59
1,80e641a11e56f04c1ad469d5645fdfde,a548910a1c6147796b98fdf73dbeba33,5,NaN,NaN,2018-03-10 00:00:00,2018-03-11 03:05:13

==================================================
PROFILE FOR TABLE: ORDERS
==================================================
Dimensions: 99441 rows, 8 columns

--- Data Types and Missing Values ---
                              Data Type  Missing Values  Missing %
order_id                         object               0       0.00
customer_id                      object               0       0.00
order_status                     object               0       0.00
order_purchase_timestamp         object               0       0.00
order_approved_at                object             160       0.16
order_delivered_carrier_date     object            1783       1.79
order_delivered_customer_date    object            2965       2.98
order_estimated_delivery_date    object               0       0.00

Duplicate Records: 0 (0.00%)

--- Sample Rows ---

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00

==================================================
PROFILE FOR TABLE: PRODUCTS
==================================================
Dimensions: 32951 rows, 9 columns

--- Data Types and Missing Values ---
                           Data Type  Missing Values  Missing %
product_id                    object               0       0.00
product_category_name         object             610       1.85
product_name_lenght          float64             610       1.85
product_description_lenght   float64             610       1.85
product_photos_qty           float64             610       1.85
product_weight_g             float64               2       0.01
product_length_cm            float64               2       0.01
product_height_cm            float64               2       0.01
product_width_cm             float64               2       0.01

Duplicate Records: 0 (0.00%)

--- Sample Rows ---

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,40.0,287.0,1.0,225.0,16.0,10.0,14.0
1,3aa071139cb16b67ca9e5dea641aaa2f,artes,44.0,276.0,1.0,1000.0,30.0,18.0,20.0

==================================================
PROFILE FOR TABLE: SELLERS
==================================================
Dimensions: 3095 rows, 4 columns

--- Data Types and Missing Values ---
                       Data Type  Missing Values  Missing %
seller_id                 object               0        0.0
seller_zip_code_prefix     int64               0        0.0
seller_city               object               0        0.0
seller_state              object               0        0.0

Duplicate Records: 0 (0.00%)

--- Sample Rows ---

,seller_id,seller_zip_code_prefix,seller_city,seller_state
0,3442f8959a84dea7ee197c632cb2df15,13023,campinas,SP
1,d1b65fc7debc3361ea86b5f14c68d2e2,13844,mogi guacu,SP

==================================================
PROFILE FOR TABLE: CATEGORY_TRANSLATION
==================================================
Dimensions: 71 rows, 2 columns

--- Data Types and Missing Values ---
                              Data Type  Missing Values  Missing %
product_category_name            object               0        0.0
product_category_name_english    object               0        0.0

Duplicate Records: 0 (0.00%)

--- Sample Rows ---

    product_category_name product_category_name_english
0            beleza_saude                 health_beauty
1  informatica_acessorios         computers_accessories

### Complete Data Dictionary

Based on the profiling, here is the business dictionary for key fields:

#### 1. `customers`
- `customer_id`: Unique key assigned to each order transaction (changes for every purchase).
- `customer_unique_id`: Persistent identifier for the physical customer (remains constant across multiple purchases).
- `customer_zip_code_prefix`: Customer's zip code (first 5 digits).
- `customer_city`: Customer's city.
- `customer_state`: Customer's state code (e.g., SP, RJ).

#### 2. `orders`
- `order_id`: Primary key for the transaction.
- `customer_id`: Foreign key linking to `customers` table.
- `order_status`: Lifecycle status (delivered, shipped, canceled, invoiced, processing, approved, created, unavailable).
- `order_purchase_timestamp`: Date and time the order was placed.
- `order_approved_at`: Date and time payment was approved.
- `order_delivered_carrier_date`: Date and time order was handed over to logistics.
- `order_delivered_customer_date`: Date and time customer received the package.
- `order_estimated_delivery_date`: Promised delivery date communicated at checkout.

#### 3. `order_items`
- `order_id`: Foreign key linking to `orders` table.
- `order_item_id`: Sequential line item number within the same order (e.g., 1, 2, 3).
- `product_id`: Foreign key linking to `products` table.
- `seller_id`: Foreign key linking to `sellers` table.
- `shipping_limit_date`: Seller shipping deadline to hand over to carrier.
- `price`: Item price (in BRL).
- `freight_value`: Shipping cost charged to customer (in BRL).

#### 4. `order_payments`
- `order_id`: Foreign key linking to `orders` table.
- `payment_sequential`: Order payment step sequence (if using multiple payment methods).
- `payment_type`: Method of payment (credit_card, boleto, voucher, debit_card, not_defined).
- `payment_installments`: Selected installment count for credit card purchases.
- `payment_value`: Total amount paid (price + freight) for that payment transaction.

#### 5. `order_reviews`
- `review_id`: Unique review identifier.
- `order_id`: Foreign key linking to `orders` table.
- `review_score`: Satisfaction rating from 1 (lowest) to 5 (highest).
- `review_comment_title`: Title of the review comment.
- `review_comment_message`: Text review left by the customer.
- `review_creation_date`: Review survey creation timestamp.
- `review_answer_timestamp`: Review submission timestamp.

#### 6. `products`
- `product_id`: Primary key for the product.
- `product_category_name`: Category name in Portuguese.
- `product_name_lenght`: Character count of the product title.
- `product_description_lenght`: Character count of the product description.
- `product_photos_qty`: Count of photos uploaded for the product.
- `product_weight_g`: Weight of product in grams.
- `product_length_cm`: Product length in centimeters.
- `product_height_cm`: Product height in centimeters.
- `product_width_cm`: Product width in centimeters.

#### 7. `sellers`
- `seller_id`: Primary key for the seller.
- `seller_zip_code_prefix`: Seller's zip code (first 5 digits).
- `seller_city`: Seller's city.
- `seller_state`: Seller's state code.

#### 8. `geolocation`
- `geolocation_zip_code_prefix`: First 5 digits of zip code.
- `geolocation_lat`: Latitude.
- `geolocation_lng`: Longitude.
- `geolocation_city`: City name.
- `geolocation_state`: State code.

#### 9. `product_category_translation`
- `product_category_name`: Portuguese category name.
- `product_category_name_english`: English category translation.